### ISSUE TITLE
Add scrapers to pull Budget data from OMB

### ISSUE THREAD

**Issue by sseshan7** [stevesdawg/govstat#15]
Follow on issue created to finish the work raised in #14.

The budget data pipeline is currently completely manual. Automating it would make this repo easier to distribute to users, allowing them to pull their own data, rather than maintainers pushing excel files to the repo.

**Comment by acxz** [comment]
How much work is this? Do you think it is worth the effort?

If this scraper is created ideally it should be part of some larger governmental scraping library so that it can reach more people. If we are going to keep this scraper in just this repo, then I honestly don't think it might be worth it.

tldr we should find a repo more widely available that could make better use of such a feature.

In the meanwhile git lfs or at least readme instructions on how to manually download the files would be of immediate value.

edit: Actually since it seems like just downloading files it may not actually be as hard as I had originally thought

**Comment by connorjoleary** [comment]
If y'all still want this done, I may be able to help. I have some experience with web scrapers. https://github.com/connorjoleary/DeepCite

But I would need a larger description of what you are trying to accomplish.

**Comment by acxz** [comment]
I think essentially this repo has a folder that contains a bunch of data files hosted via git lfs. If we can create a python script that downloads these files that would resolve this issue. https://github.com/stevesdawg/govstat/tree/main/data/hist_fy21

As for the source of these files it should be this right here: https://www.whitehouse.gov/omb/budget/historical-tables/ which isn't too bad as I think even just a simple bash script can do the job of `curl`ing/`wget`ing the urls with the xlsx files.

**Comment by connorjoleary** [comment]
Gotcha, I should be able to create a tool which downloads all of the linked files from https://www.whitehouse.gov/omb/budget/historical-tables/ into the folder `data/hist_fy21`. Probably will use python because idk how to parse a website with bash.

Also, not sure the end goal for this info, but https://www.govinfo.gov/app/collection/budget/2023 may be a better source because they provide a good api for their data.
